export const CITIES = [
	{ id: "Abbottabad", name: "Abbottabad" },
	{ id: "Abdul Hakim", name: "Abdul Hakim" },
	{ id: "Ahmadpur East", name: "Ahmadpur East" },
	{ id: "Ahmadpur Sial", name: "Ahmadpur Sial" },
	{ id: "Akora Khattak", name: "Akora Khattak" },
	{ id: "Alipur", name: "Alipur" },
	{ id: "Alipur Chattha", name: "Alipur Chattha" },
	{ id: "Alpurai", name: "Alpurai" },
	{ id: "Arifwala", name: "Arifwala" },
	{ id: "Athmuqam", name: "Athmuqam" },
	{ id: "Attock", name: "Attock" },
	{ id: "Awaran", name: "Awaran" },
	{ id: "Badin", name: "Badin" },
	{ id: "Bagh", name: "Bagh" },
	{ id: "Bahawalnagar", name: "Bahawalnagar" },
	{ id: "Bahawalpur", name: "Bahawalpur" },
	{ id: "Bajaur", name: "Bajaur" },
	{ id: "Balakot", name: "Balakot" },
	{ id: "Bannu", name: "Bannu" },
	{ id: "Barkhan", name: "Barkhan" },
	{ id: "Barnala", name: "Barnala" },
	{ id: "Basirpur", name: "Basirpur" },
	{ id: "Batkhela", name: "Batkhela" },
	{ id: "Battagram", name: "Battagram" },
	{ id: "Bhakkar", name: "Bhakkar" },
	{ id: "Bhalwal", name: "Bhalwal" },
	{ id: "Bhera", name: "Bhera" },
	{ id: "Bhimber", name: "Bhimber" },
	{ id: "Bhiria City", name: "Bhiria City" },
	{ id: "Booni", name: "Booni" },
	{ id: "Buner", name: "Buner" },
	{ id: "Burewala", name: "Burewala" },
	{ id: "Chakdara", name: "Chakdara" },
	{ id: "Chakwal", name: "Chakwal" },
	{ id: "Chaman", name: "Chaman" },
	{ id: "Charsadda", name: "Charsadda" },
	{ id: "Chawinda", name: "Chawinda" },
	{ id: "Chenab Nagar", name: "Chenab Nagar" },
	{ id: "Chichawatni", name: "Chichawatni" },
	{ id: "Chilas", name: "Chilas" },
	{ id: "Chiniot", name: "Chiniot" },
	{ id: "Chishtian", name: "Chishtian" },
	{ id: "Chitral", name: "Chitral" },
	{ id: "Choa Saidan Shah", name: "Choa Saidan Shah" },
	{ id: "Chunian", name: "Chunian" },
	{ id: "Dadu", name: "Dadu" },
	{ id: "Dadyal", name: "Dadyal" },
	{ id: "Daharki", name: "Daharki" },
	{ id: "Daska", name: "Daska" },
	{ id: "Daur", name: "Daur" },
	{ id: "Depalpur", name: "Depalpur" },
	{ id: "Dera Allah Yar", name: "Dera Allah Yar" },
	{ id: "Dera Bugti", name: "Dera Bugti" },
	{ id: "Dera Ghazi Khan", name: "Dera Ghazi Khan" },
	{ id: "Dera Ismail Khan", name: "Dera Ismail Khan" },
	{ id: "Dera Murad Jamali", name: "Dera Murad Jamali" },
	{ id: "Digri", name: "Digri" },
	{ id: "Dina", name: "Dina" },
	{ id: "Dinga", name: "Dinga" },
	{ id: "Dir", name: "Dir" },
	{ id: "Dokri", name: "Dokri" },
	{ id: "Drosh", name: "Drosh" },
	{ id: "Duniyapur", name: "Duniyapur" },
	{ id: "Faisalabad", name: "Faisalabad" },
	{ id: "Farooqabad", name: "Farooqabad" },
	{ id: "Fateh Jang", name: "Fateh Jang" },
	{ id: "Fazilpur", name: "Fazilpur" },
	{ id: "Fort Abbas", name: "Fort Abbas" },
	{ id: "Gahkuch", name: "Gahkuch" },
	{ id: "Gakkhar Mandi", name: "Gakkhar Mandi" },
	{ id: "Gambat", name: "Gambat" },
	{ id: "Garhi Habibullah", name: "Garhi Habibullah" },
	{ id: "Ghotki", name: "Ghotki" },
	{ id: "Gilgit", name: "Gilgit" },
	{ id: "Gogera", name: "Gogera" },
	{ id: "Gojra", name: "Gojra" },
	{ id: "Gujar Khan", name: "Gujar Khan" },
	{ id: "Gujranwala", name: "Gujranwala" },
	{ id: "Gujrat", name: "Gujrat" },
	{ id: "Gwadar", name: "Gwadar" },
	{ id: "Hafizabad", name: "Hafizabad" },
	{ id: "Hangu", name: "Hangu" },
	{ id: "Haripur", name: "Haripur" },
	{ id: "Harnai", name: "Harnai" },
	{ id: "Hasilpur", name: "Hasilpur" },
	{ id: "Hassan Abdal", name: "Hassan Abdal" },
	{ id: "Haveli Lakha", name: "Haveli Lakha" },
	{ id: "Havelian", name: "Havelian" },
	{ id: "Hazro", name: "Hazro" },
	{ id: "Hub", name: "Hub" },
	{ id: "Hujra Shah Muqeem", name: "Hujra Shah Muqeem" },
	{ id: "Hunza", name: "Hunza" },
	{ id: "Hyderabad", name: "Hyderabad" },
	{ id: "Islamabad", name: "Islamabad" },
	{ id: "Islamkot", name: "Islamkot" },
	{ id: "Jacobabad", name: "Jacobabad" },
	{ id: "Jalalpur Jattan", name: "Jalalpur Jattan" },
	{ id: "Jand", name: "Jand" },
	{ id: "Jampur", name: "Jampur" },
	{ id: "Jaranwala", name: "Jaranwala" },
	{ id: "Jati", name: "Jati" },
	{ id: "Jatoi", name: "Jatoi" },
	{ id: "Jauharabad", name: "Jauharabad" },
	{ id: "Jhang", name: "Jhang" },
	{ id: "Jhelum", name: "Jhelum" },
	{ id: "Johi", name: "Johi" },
	{ id: "Kabirwala", name: "Kabirwala" },
	{ id: "Kahror Pakka", name: "Kahror Pakka" },
	{ id: "Kahuta", name: "Kahuta" },
	{ id: "Kala Shah Kaku", name: "Kala Shah Kaku" },
	{ id: "Kalabagh", name: "Kalabagh" },
	{ id: "Kalar Kahar", name: "Kalar Kahar" },
	{ id: "Kalat", name: "Kalat" },
	{ id: "Kamalia", name: "Kamalia" },
	{ id: "Kamoke", name: "Kamoke" },
	{ id: "Kamra", name: "Kamra" },
	{ id: "Kandhkot", name: "Kandhkot" },
	{ id: "Kandiaro", name: "Kandiaro" },
	{ id: "Karak", name: "Karak" },
	{ id: "Karachi", name: "Karachi" },
	{ id: "Kasur", name: "Kasur" },
	{ id: "Kashmore", name: "Kashmore" },
	{ id: "Khangarh", name: "Khangarh" },
	{ id: "Khairpur", name: "Khairpur" },
	{ id: "Khanewal", name: "Khanewal" },
	{ id: "Khanpur", name: "Khanpur" },
	{ id: "Khaplu", name: "Khaplu" },
	{ id: "Kharan", name: "Kharan" },
	{ id: "Kharian", name: "Kharian" },
	{ id: "Khewra", name: "Khewra" },
	{ id: "Khipro", name: "Khipro" },
	{ id: "Khushab", name: "Khushab" },
	{ id: "Khuzdar", name: "Khuzdar" },
	{ id: "Kohat", name: "Kohat" },
	{ id: "Kohlu", name: "Kohlu" },
	{ id: "Kot Addu", name: "Kot Addu" },
	{ id: "Kot Momin", name: "Kot Momin" },
	{ id: "Kotla Arab Ali Khan", name: "Kotla Arab Ali Khan" },
	{ id: "Kotli", name: "Kotli" },
	{ id: "Kotri", name: "Kotri" },
	{ id: "Kundian", name: "Kundian" },
	{ id: "Kunri", name: "Kunri" },
	{ id: "Lachi", name: "Lachi" },
	{ id: "Lahore", name: "Lahore" },
	{ id: "Lalamusa", name: "Lalamusa" },
	{ id: "Lalian", name: "Lalian" },
	{ id: "Lakki Marwat", name: "Lakki Marwat" },
	{ id: "Larkana", name: "Larkana" },
	{ id: "Layyah", name: "Layyah" },
	{ id: "Liaquatpur", name: "Liaquatpur" },
	{ id: "Lodhran", name: "Lodhran" },
	{ id: "Loralai", name: "Loralai" },
	{ id: "Mailsi", name: "Mailsi" },
	{ id: "Malakand", name: "Malakand" },
	{ id: "Malakwal", name: "Malakwal" },
	{ id: "Mandi Bahauddin", name: "Mandi Bahauddin" },
	{ id: "Mandra", name: "Mandra" },
	{ id: "Manga Mandi", name: "Manga Mandi" },
	{ id: "Mangla", name: "Mangla" },
	{ id: "Mankera", name: "Mankera" },
	{ id: "Mansehra", name: "Mansehra" },
	{ id: "Mardan", name: "Mardan" },
	{ id: "Mastung", name: "Mastung" },
	{ id: "Matiari", name: "Matiari" },
	{ id: "Matli", name: "Matli" },
	{ id: "Matta", name: "Matta" },
	{ id: "Mehar", name: "Mehar" },
	{ id: "Mehrabpur", name: "Mehrabpur" },
	{ id: "Mian Channu", name: "Mian Channu" },
	{ id: "Mianwali", name: "Mianwali" },
	{ id: "Minchinabad", name: "Minchinabad" },
	{ id: "Mingora", name: "Mingora" },
	{ id: "Miram Shah", name: "Miram Shah" },
	{ id: "Mirpur", name: "Mirpur" },
	{ id: "Mirpur Khas", name: "Mirpur Khas" },
	{ id: "Mirokhan", name: "Mirokhan" },
	{ id: "Mithi", name: "Mithi" },
	{ id: "Moro", name: "Moro" },
	{ id: "Multan", name: "Multan" },
	{ id: "Muridke", name: "Muridke" },
	{ id: "Murree", name: "Murree" },
	{ id: "Muzaffarabad", name: "Muzaffarabad" },
	{ id: "Muzaffargarh", name: "Muzaffargarh" },
	{ id: "Nankana Sahib", name: "Nankana Sahib" },
	{ id: "Narang Mandi", name: "Narang Mandi" },
	{ id: "Narowal", name: "Narowal" },
	{ id: "Nasarpur", name: "Nasarpur" },
	{ id: "Nasirabad", name: "Nasirabad" },
	{ id: "Naudero", name: "Naudero" },
	{ id: "Naukot", name: "Naukot" },
	{ id: "Naushahro Feroze", name: "Naushahro Feroze" },
	{ id: "Nawabshah", name: "Nawabshah" },
	{ id: "Noorpur", name: "Noorpur" },
	{ id: "Nowshera", name: "Nowshera" },
	{ id: "Okara", name: "Okara" },
	{ id: "Ormara", name: "Ormara" },
	{ id: "Pabbi", name: "Pabbi" },
	{ id: "Paharpur", name: "Paharpur" },
	{ id: "Pakpattan", name: "Pakpattan" },
	{ id: "Palandri", name: "Palandri" },
	{ id: "Panjgur", name: "Panjgur" },
	{ id: "Pano Aqil", name: "Pano Aqil" },
	{ id: "Parachinar", name: "Parachinar" },
	{ id: "Pasni", name: "Pasni" },
	{ id: "Pasrur", name: "Pasrur" },
	{ id: "Pattoki", name: "Pattoki" },
	{ id: "Peshawar", name: "Peshawar" },
	{ id: "Phalia", name: "Phalia" },
	{ id: "Pind Dadan Khan", name: "Pind Dadan Khan" },
	{ id: "Pindi Bhattian", name: "Pindi Bhattian" },
	{ id: "Pindi Gheb", name: "Pindi Gheb" },
	{ id: "Pir Jo Goth", name: "Pir Jo Goth" },
	{ id: "Pir Mahal", name: "Pir Mahal" },
	{ id: "Piplan", name: "Piplan" },
	{ id: "Pishin", name: "Pishin" },
	{ id: "Qambar", name: "Qambar" },
	{ id: "Qazi Ahmed", name: "Qazi Ahmed" },
	{ id: "Qila Abdullah", name: "Qila Abdullah" },
	{ id: "Qila Deedar Singh", name: "Qila Deedar Singh" },
	{ id: "Qila Saifullah", name: "Qila Saifullah" },
	{ id: "Quetta", name: "Quetta" },
	{ id: "Rabwah", name: "Rabwah" },
	{ id: "Rahim Yar Khan", name: "Rahim Yar Khan" },
	{ id: "Raiwind", name: "Raiwind" },
	{ id: "Rajanpur", name: "Rajanpur" },
	{ id: "Ratodero", name: "Ratodero" },
	{ id: "Rawalakot", name: "Rawalakot" },
	{ id: "Rawalpindi", name: "Rawalpindi" },
	{ id: "Renala Khurd", name: "Renala Khurd" },
	{ id: "Risalpur", name: "Risalpur" },
	{ id: "Rohri", name: "Rohri" },
	{ id: "Rojhan", name: "Rojhan" },
	{ id: "Rustam", name: "Rustam" },
	{ id: "Sadda", name: "Sadda" },
	{ id: "Sadiqabad", name: "Sadiqabad" },
	{ id: "Sahiwal", name: "Sahiwal" },
	{ id: "Sakrand", name: "Sakrand" },
	{ id: "Sambrial", name: "Sambrial" },
	{ id: "Sanghar", name: "Sanghar" },
	{ id: "Sangla Hill", name: "Sangla Hill" },
	{ id: "Sarai Alamgir", name: "Sarai Alamgir" },
	{ id: "Sarai Naurang", name: "Sarai Naurang" },
	{ id: "Sargodha", name: "Sargodha" },
	{ id: "Sehwan", name: "Sehwan" },
	{ id: "Shabqadar", name: "Shabqadar" },
	{ id: "Shahdadkot", name: "Shahdadkot" },
	{ id: "Shahdadpur", name: "Shahdadpur" },
	{ id: "Shahkot", name: "Shahkot" },
	{ id: "Shahpur Chakar", name: "Shahpur Chakar" },
	{ id: "Shahpur City", name: "Shahpur City" },
	{ id: "Shakargarh", name: "Shakargarh" },
	{ id: "Shangla", name: "Shangla" },
	{ id: "Sharaqpur", name: "Sharaqpur" },
	{ id: "Sheikhupura", name: "Sheikhupura" },
	{ id: "Sherani", name: "Sherani" },
	{ id: "Shikarpur", name: "Shikarpur" },
	{ id: "Shorkot", name: "Shorkot" },
	{ id: "Shujaabad", name: "Shujaabad" },
	{ id: "Sialkot", name: "Sialkot" },
	{ id: "Sibbi", name: "Sibbi" },
	{ id: "Sillanwali", name: "Sillanwali" },
	{ id: "Skardu", name: "Skardu" },
	{ id: "Sohawa", name: "Sohawa" },
	{ id: "Sui", name: "Sui" },
	{ id: "Sujawal", name: "Sujawal" },
	{ id: "Sukkur", name: "Sukkur" },
	{ id: "Swabi", name: "Swabi" },
	{ id: "Swat", name: "Swat" },
	{ id: "Takht Bhai", name: "Takht Bhai" },
	{ id: "Talagang", name: "Talagang" },
	{ id: "Talhar", name: "Talhar" },
	{ id: "Tandlianwala", name: "Tandlianwala" },
	{ id: "Tando Adam", name: "Tando Adam" },
	{ id: "Tando Allahyar", name: "Tando Allahyar" },
	{ id: "Tando Bago", name: "Tando Bago" },
	{ id: "Tando Jan Muhammad", name: "Tando Jan Muhammad" },
	{ id: "Tando Muhammad Khan", name: "Tando Muhammad Khan" },
	{ id: "Tank", name: "Tank" },
	{ id: "Taunsa", name: "Taunsa" },
	{ id: "Taxila", name: "Taxila" },
	{ id: "Thatta", name: "Thatta" },
	{ id: "Thul", name: "Thul" },
	{ id: "Timergara", name: "Timergara" },
	{ id: "Toba Tek Singh", name: "Toba Tek Singh" },
	{ id: "Topi", name: "Topi" },
	{ id: "Turbat", name: "Turbat" },
	{ id: "Ubauro", name: "Ubauro" },
	{ id: "Uch Sharif", name: "Uch Sharif" },
	{ id: "Umerkot", name: "Umerkot" },
	{ id: "Usta Muhammad", name: "Usta Muhammad" },
	{ id: "Uthal", name: "Uthal" },
	{ id: "Vehari", name: "Vehari" },
	{ id: "Wah Cantonment", name: "Wah Cantonment" },
	{ id: "Wana", name: "Wana" },
	{ id: "Warburton", name: "Warburton" },
	{ id: "Wazirabad", name: "Wazirabad" },
	{ id: "Yazman", name: "Yazman" },
	{ id: "Zafarwal", name: "Zafarwal" },
	{ id: "Zahir Pir", name: "Zahir Pir" },
	{ id: "Zhob", name: "Zhob" },
	{ id: "Ziarat", name: "Ziarat" },
];
