import { TEmployeeSalaryHistory } from "@/types/Employee";

export const EMPLOYEE_SALARY_HISTORY_DUMMY_DATA: TEmployeeSalaryHistory[] = [
	{
		_id: "employee-salary-history-1",
		month: "Jan, 2026",
		note: "Salary paid with additional performance commission.",
		on_time: "29 days",
		late: "1 day",
		absence: "0 day",
		leave: "0 day",
		base_salary: 25000,
		commission: 10000,
		other: 0,
		paid_at: "Feb 1, 2026",
		created_at: "Feb 1, 2026",
	},
	{
		_id: "employee-salary-history-2",
		month: "Dec, 2025",
		note: "Two late marks and two absences were recorded this month.",
		on_time: "27 days",
		late: "2 days",
		absence: "2 days",
		leave: "0 day",
		base_salary: 25000,
		commission: 5000,
		other: 0,
		paid_at: "Jan 1, 2026",
		created_at: "Jan 1, 2026",
	},
	{
		_id: "employee-salary-history-3",
		month: "Nov, 2025",
		on_time: "30 days",
		late: "0 day",
		absence: "0 day",
		leave: "0 day",
		base_salary: 25000,
		commission: 5000,
		other: 500,
		paid_at: "Dec 1, 2025",
		created_at: "Dec 1, 2025",
	},
];
