export const ERROR_MESSAGES = {
	unauthorized: "Unauthorized",
	password: "Password must be at least 8 characters long.",
	passwordRequired: "Password is required.",
	name: "Name must be at least 4 characters.",
	nameInvalid: "Name should only contain alphabets.",
	designationInvalid: "Designation should only contain alphabets.",
	productName: "Maximum 80 characters allowed for product name",
	nameRequired: "Name is required.",
	email: "Invalid email address.",
	emailRequired: "Email is required.",
	designationRequired: "Designation is required.",
	userExists: "User already exists.",
	signin: "Invalid email or password.",
	user: "User not found.",
	productExists: "Product with this sku or barcode already exists.",
	product: "Product not found.",
	somethingWentWrong: "Something went wrong.",
	productNotExists: "Product with this sku not exists.",
	productQty: "Product quantity not found.",
	order: "Order not found.",
	phone: "Phone no is required.",
	phoneInvalid: "Phone no is invalid.",
	phoneLeast: "Phone no must be atleast 11 digits.",
	leastAccess: "At least one access is required.",
	recieved_amount: "Received amount is required",
	permissionDenied: "Permission denied",
	barcode: "Maximum 80 characters allowed in Barcode.",
	barcodeRequired: "Barcode is required",
	sku: "Maximum 80 characters allowed in SKU",
	skuRequired: "SKU is required",
	specialCharacters: "Special characters are not allowed.",
	price: "Price must be positive",
	lowStockIndicator: "Low stock quantity must be positive.",
	lowStockIndicatorNotDecimal: "Low stock quantity cannot be decimals.",
	priceRequired: "Price is required",
	LowStockRequired: "Low stock quantity is required.",
	cost: "Cost must be positive",
	costRequired: "Cost is required",
	quantity: "Quantity must be positive",
	quantityRequired: "Quantity is required",
	reason: "Reason is required",
	discount: "Discount should not be negative",
	inValidCSV: "Only .csv files are supported",
	logoUrl: "Logo URL must be a valid URL",
	facebook: "Maximum 100 characters allowed in Facebook",
	instagram: "Maximum 100 characters allowed in Instagram",
	snapchat: "Maximum 100 characters allowed in Snapchat",
	x: "Maximum 100 characters allowed in X",
	youtube: "Maximum 100 characters allowed in Youtube",
	shopify_Store_Key: "Maximum 100 characters allowed in store key",
	shopify_api_key: "Maximum 100 characters allowed in api key",
	shopRequired: "Shop is required",
	vendorRequired: "Vendor is required",
	dateRequired: "Date is required",
	itemsRequired: "At least one item is required",
	billIdRequired: "Bill ID is required",
	billNoRequired: "Bill number is required",
	cnicRequired: "CNIC is required.",
	cnicInvalid: "CNIC must be in XXXXX-XXXXXXX-X format.",
	employeeExists: "Employee with this CNIC already exists.",
	baseSalaryInvalid: "Base salary must be a positive number.",
	commissionInvalid: "Commission should not be negative.",
	otherAmountInvalid: "Other amount should not be negative.",
	addressRequired: "Address is required.",
	joinedAtRequired: "Joined date is required.",
	joinedAtFuture: "Joined date cannot be in the future.",
	statusRequired: "Employment status is required.",
	statusInvalid: "Select a valid status.",
	paymentMonthRequired: "Payment month is required.",
	paymentMonthFuture: "Payment month cannot be in the future.",
	paidAtRequired: "Paid date is required.",
	employeeRequired: "Employee is required.",
	markRequired: "Mark is required.",
	attendanceDateTimeRequired: "Attendance date and time is required.",
	attendanceDateTimeInvalid: "Invalid attendance date and time.",
	attendanceDateTimeFuture: "Future date/time is not allowed.",
};
